import { Property, Testimonial, Stat } from './types';

export const properties: Property[] = [
  {
    id: 'prop-1',
    transactionType: 'venta',
    title: 'Manuel Antonio Castro',
    subtitle: 'Ante esquina Paso de los Libres',
    price: 'Consultar Precio',
    priceNumeric: 0,
    location: '20 de Junio, La Matanza',
    streets: 'Manuel A. Castro y Paso de los Libres',
    mercadoLibreLink: 'https://terreno.mercadolibre.com.ar/MLA-2627762324-terreno-en-venta-20-de-junio-_JM',
    category: 'terrenos',
    image: '/venta/terrenos/Terreno-Manual-Antonio-Castro-y-1200-PasodeLoslibres--PORTADA--.webp',
    images: [
      '/venta/terrenos/Terreno-Manual-Antonio-Castro-y-1200-PasodeLoslibres--PORTADA--.webp',
      '/venta/terrenos/Terreno-Manual-Antonio-Castro-y-1200-PasodeLoslibres--1--.webp',
      '/venta/terrenos/Terreno-Manual-Antonio-Castro-y-1200-PasodeLoslibres--2--.webp'
    ],
    description: 'Terreno en Venta – Parcela 9 (Ante esquina)\nUbicación: Manuel Castro, 20 de Junio, La Matanza.\n\nExcelente oportunidad de inversión en una de las zonas más buscadas de 20 de Junio. La parcela se encuentra ubicada en ante esquina entre Manuel Castro y Paso de los Libres, a solo una cuadra del asfalto, con un entorno óptimo y vecinos linderos que cuentan principalmente con casas quintas, aportando tranquilidad y buena convivencia.\n\nDimensiones y características:\n• Frente: 27 metros\n• Fondo: 55 metros\n• Superficie total: 1.500 m²\n\nPosee una arboleda frondosa, destacándose varias acacias que brindan una sombra natural ideal para disfrutar del espacio verde. El lote ofrece una superficie amplia y aprovechable para diversos proyectos.\n\nIdeal para vivienda, descanso de fin de semana o inversión a futuro.\n\nIVANA MOLINA & ASOC. BIENES RAÍCES\nMAT 1048\nCDMDLM',
    beds: 0,
    baths: 0,
    area: '1,500 m²',
    features: ['Arboleda Frondosa', 'Zona Residencial (Quintas)', 'A 100m del asfalto', 'Inversión Segura'],
    coordinates: { x: 35, y: 40 },
    isFeatured: true,
    isMostWanted: true,
  },
  {
    id: 'prop-2',
    transactionType: 'venta',
    title: 'Lote en Alejo Castex',
    subtitle: 'Dos terrenos contiguos (3000 m²)',
    price: 'Consultar Precio',
    priceNumeric: 0,
    location: '20 de Junio, La Matanza',
    streets: 'Alejo Castex y Manuel A. Castro',
    mercadoLibreLink: 'https://terreno.mercadolibre.com.ar/MLA-2587214160-dos-terrenos-a-la-venta-20-de-junio-_JM',
    category: 'terrenos',
    image: '/venta/terrenos/Terreno-alejo-castex-portada.webp',
    images: [
      '/venta/terrenos/Terreno-alejo-castex-portada.webp',
      '/venta/terrenos/Terreno-Alejo-Castex-1.webp'
    ],
    description: 'TERRENO 3000 m² ALEJO CASTEX, 20 DE JUNIO, LA MATANZA\n\nSe venden dos terrenos contiguos, cada uno con salida a distintas calles, ofreciendo una ubicación estratégica y múltiple accesibilidad.\n• Terreno 1 con frente a Alejo Castex\n• Terreno 2 con frente a Manuel Castro\n\nAmbos lotes se encuentran parquizados, alambrados y arbolados, ideales para quienes buscan un entorno natural y listo para proyectar.\n\nCada terreno posee:\n• 27,50 metros de frente\n• 55 metros de fondo\n• Superficie total aproximada: 1.512 m² por lote\n\nLa ubicación es excelente: zona tranquila, en pleno centro de 20 de Junio, con cercanía a comercios, transporte y rápido acceso a las principales arterias. Perfectos para proyecto residencial, emprendimiento o inversión.\n\nIVANA MOLINA & ASOC. BIENES RAÍCES\nMAT 1048\nCDMDLM',
    beds: 0,
    baths: 0,
    area: '3,000 m²',
    features: ['Doble Acceso por Calles Diferentes', 'Parquizado y Alambrado', 'Ubicación Estratégica Céntrica', 'Lotes Subdividibles'],
    coordinates: { x: 58, y: 25 },
    isFeatured: true,
    isMostWanted: true,
  },
  {
    id: 'prop-3',
    transactionType: 'venta',
    title: 'Cosquín 1400',
    subtitle: 'Casa Quinta – Terreno de 1.610 m²',
    price: 'Consultar Precio',
    priceNumeric: 0,
    location: '20 de Junio, La Matanza',
    streets: 'Cosquín y Manuel Castro',
    mercadoLibreLink: 'https://casa.mercadolibre.com.ar/MLA-1557210415-casa-quinta-en-venta-20-de-junio-terreno-1610-m2-_JM',
    category: 'casas-quinta',
    image: '/venta/casas-quinta/COSQUIN 1400-Casa Quinta En Ven/COSQUIN 1400-Casa Quinta En Venta- 1.webp',
    images: [
      '/venta/casas-quinta/COSQUIN 1400-Casa Quinta En Ven/COSQUIN 1400-Casa Quinta En Venta- 1.webp',
      '/venta/casas-quinta/COSQUIN 1400-Casa Quinta En Ven/COSQUIN 1400-Casa Quinta En Vent-2.webp',
      '/venta/casas-quinta/COSQUIN 1400-Casa Quinta En Ven/COSQUIN 1400-Casa Quinta En Vent-3.webp',
      '/venta/casas-quinta/COSQUIN 1400-Casa Quinta En Ven/COSQUIN 1400-Casa Quinta En Vent-4.webp',
      '/venta/casas-quinta/COSQUIN 1400-Casa Quinta En Ven/COSQUIN 1400-Casa Quinta En Vent-5.webp',
      '/venta/casas-quinta/COSQUIN 1400-Casa Quinta En Ven/COSQUIN 1400-Casa Quinta En Vent-6.webp',
      '/venta/casas-quinta/COSQUIN 1400-Casa Quinta En Ven/COSQUIN 1400-Casa Quinta En Vent-7.webp'
    ],
    description: 'Casa Quinta en Venta – 20 de Junio, La Matanza\nUbicación: Cosquín y Manuel Castro (casi en el ingreso a la localidad).\n\nEsta propiedad ofrece una ubicación privilegiada dentro de un entorno tranquilo y natural. Sobre un terreno de 1.610 m² con una particular forma de diamante y rodeado de árboles añosos, se desarrolla una cálida casa con un diseño funcional y excelente iluminación natural.\n\nLa vivienda cuenta con una cocina integrada a un amplio living-comedor, un espacio abierto y luminoso ideal para disfrutar en familia. Un pasillo distribuidor conecta con un baño completo y la habitación principal en planta baja. En la planta alta se encuentra una segunda habitación que amplía las posibilidades de uso.\n\nEn el exterior, la propiedad dispone de un baño adicional, un cuarto de herramientas y una pileta de aproximadamente 9 x 4 metros, rodeada de verde y total privacidad, ideal para disfrutar de los días de descanso. Una opción perfecta para quienes buscan naturaleza, comodidad y una excelente ubicación a pocos minutos de la ciudad.\n\n*Las imágenes han sido optimizadas mediante herramientas de inteligencia artificial con el único fin de mejorar la calidad visual (iluminación, nitidez) y eliminar elementos circunstanciales que no aportan a la lectura del espacio. No se han modificado dimensiones, distribución ni características estructurales del inmueble.*\n\nMOLINA IVANA & ASOC. BIENES RAÍCES\nMAT 1048 – COLEGIO DE MARTILLEROS DE LA MATANZA',
    beds: 2,
    baths: 2,
    area: '1.610 m²',
    features: ['Pileta de 9x4 m', 'Terreno de 1.610 m²', 'Arboleda Añosa', 'Excelente Ubicación en Esquina'],
    coordinates: { x: 45, y: 55 },
    isFeatured: true,
    isMostWanted: true,
  },
  {
    id: 'prop-4',
    transactionType: 'venta',
    title: 'Castañeda y Cosquín',
    subtitle: 'Casa Quinta con Piscina – Terreno de 1.500 m²',
    price: 'Consultar Precio',
    priceNumeric: 0,
    location: '20 de Junio, La Matanza',
    streets: 'Castañeda y Cosquín',
    mercadoLibreLink: 'https://casa.mercadolibre.com.ar/MLA-2429890272-casa-quinta-en-venta-en-20-de-junio-con-piscina-terreno-1500-m2-_JM',
    category: 'casas-quinta',
    image: '/venta/casas-quinta/CasaQuinta_Venta_20DeJunio_Piscina_1500m2/1.webp',
    images: [
      '/venta/casas-quinta/CasaQuinta_Venta_20DeJunio_Piscina_1500m2/1.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_20DeJunio_Piscina_1500m2/2.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_20DeJunio_Piscina_1500m2/3.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_20DeJunio_Piscina_1500m2/4.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_20DeJunio_Piscina_1500m2/5.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_20DeJunio_Piscina_1500m2/6.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_20DeJunio_Piscina_1500m2/8.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_20DeJunio_Piscina_1500m2/9.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_20DeJunio_Piscina_1500m2/13.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_20DeJunio_Piscina_1500m2/14.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_20DeJunio_Piscina_1500m2/15.webp'
    ],
    description: 'Casa Quinta en Venta – 20 de Junio, La Matanza\nUbicación: Castañeda esquina Cosquín, 20 de Junio, La Matanza.\n\nUbicada en una excelente esquina con acceso por asfalto, esta cálida propiedad se desarrolla sobre un importante terreno parquizado de 1.500 m² con cerco perimetral y una añosa arboleda que brinda una agradable sombra natural.\n\nDimensiones y características principales:\n• Superficie del terreno: 1.500 m²\n• Superficie cubierta: 144,87 m²\n• Acceso por hall exterior y garaje techado.\n\nDistribución interior:\n• Amplio living-comedor.\n• Cocina independiente.\n• 3 habitaciones.\n• 2 baños completos.\n\nEspacio exterior y jardín:\n• Gran piscina de natación de aproximadamente 9,50 x 4,90 metros.\n• Quincho cerrado equipado con cocina, parrilla, horno de barro y un baño completo adicional.\n• Jardín completamente parquizado y arbolado.\n\nInformación destacada:\n• ¡Apto crédito hipotecario! (Posee planos registrados, consultar detalles).\n• IMPORTANTE: Se toma propiedad en parte de pago en las localidades de San Bernardo o Mar del Plata.\n\nIVANA MOLINA & ASOC. BIENES RAÍCES\nMAT 1048 – CDMDLM',
    beds: 3,
    baths: 3,
    area: '1.500 m²',
    features: ['Piscina 9.5x4.9 m', 'Terreno de 1.500 m²', 'Apta Crédito Hipotecario', 'Quincho con Horno de Barro'],
    coordinates: { x: 40, y: 48 },
    isFeatured: true,
    isMostWanted: true,
  },
  {
    id: 'prop-5',
    transactionType: 'venta',
    title: 'Cosquín 1120',
    subtitle: 'Casa Quinta Apto Crédito – Terreno de 1.347 m²',
    price: 'Consultar Precio',
    priceNumeric: 0,
    location: '20 de Junio, La Matanza',
    streets: 'Cosquín 1120',
    mercadoLibreLink: 'https://inmueble.mercadolibre.com.ar/MLA-2003958026-casa-quinta-en-venta-terreno-1347-m2-apto-credito-_JM',
    category: 'casas-quinta',
    image: '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/1.webp',
    images: [
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/1.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/2.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/3.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/4.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/5.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/6.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/7.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/8.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/9.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/10.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/11.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/12.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/13.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/14.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/15.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/16.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/17.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/18.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/19.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/20.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/21.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/22.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/23.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/24.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/25.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/26.webp'
    ],
    description: 'Casa Quinta en Venta – 20 de Junio, La Matanza\nUbicación: Cosquín 1120, 20 de Junio, La Matanza.\n\nExcelente propiedad en venta que se destaca por su gran nivel de comodidad, excelente ubicación y sistema de riego instalado en todo el terreno.\n\nDimensiones y características principales:\n• Superficie del terreno: 1.347 m²\n• Pileta de 8 x 4 metros con solárium de 3 x 3 metros.\n• Cochera semicubierta y garaje cubierto con capacidad para 3 autos.\n\nDistribución interior:\n• 3 habitaciones de cómodas dimensiones (4 x 4 metros), una de ellas en suite.\n• Cocina, comedor y living integrados en un amplio espacio funcional.\n• 2 baños completos en total para el interior.\n• 1 toilette de recepción.\n\nEspacio exterior:\n• Amplia galería con parrilla.\n• Baño exterior exclusivo para el área de la pileta.\n• Gran parque parquizado.\n\nInformación y condiciones destacadas:\n• ¡Apta crédito hipotecario!\n• Se toma departamento en Zona Oeste o Capital Federal en parte de pago.\n• Se acepta permuta de mayor valor en las siguientes zonas: Castelar, Ituzaingó y Parque Leloir.\n\nMOLINA IVANA & ASOC. BIENES RAÍCES\nMAT 1048 – CDMDLM',
    beds: 3,
    baths: 4,
    area: '1.347 m²',
    features: ['Pileta 8x4m + Solárium', 'Lote de 1.347 m²', 'Apta Crédito Hipotecario', 'Cochera para 3 Autos', 'Riego por Aspersión'],
    coordinates: { x: 42, y: 52 },
    isFeatured: true,
    isMostWanted: true,
  },
  {
    id: 'prop-6',
    transactionType: 'venta',
    title: 'Juan Casacuberta',
    subtitle: 'Terrenos en Venta (Lotes 18 y 19) – 546 m² c/u',
    price: 'Consultar Precio',
    priceNumeric: 0,
    location: '20 de Junio, La Matanza',
    streets: 'Juan Casacuberta, entre Cóndor y Corona',
    mercadoLibreLink: 'https://terreno.mercadolibre.com.ar/MLA-2704874184-terrenos-en-venta-546-metros-20-de-junio--_JM',
    category: 'terrenos',
    image: '/venta/terrenos/Terreno_Venta_JuanCasacuberta_20DeJunio_LaMatanza/PORTADA-1.webp',
    images: [
      '/venta/terrenos/Terreno_Venta_JuanCasacuberta_20DeJunio_LaMatanza/PORTADA-1.webp',
      '/venta/terrenos/Terreno_Venta_JuanCasacuberta_20DeJunio_LaMatanza/foto-2.webp'
    ],
    description: 'Terrenos en Venta – Juan Casacuberta, 20 de Junio\nUbicación: Calle Juan Casacuberta, entre Cóndor y Corona, localidad de 20 de Junio, La Matanza.\n\nExcelente oportunidad de adquisición de lotes individuales o en conjunto. Se trata de dos terrenos contiguos (Lotes 18 y 19) parquizados, con una hermosa arboleda natural y listos para construir.\n\nCaracterísticas y dimensiones (cada lote):\n• Frente: 13 metros\n• Fondo: 42 metros\n• Superficie total: 546 m² por lote\n\nUbicación y entorno:\n• A solo 2 cuadras y media del asfalto.\n• Ubicados frente al campo, en una zona sumamente tranquila y rodeada de naturaleza.\n• Excelente entorno con gran potencial de desarrollo y crecimiento.\n\nInformación comercial:\n• Los lotes se venden por separado.\n• El valor publicado es individual (por cada uno).\n• Se escuchan ofertas por la compra de ambos lotes juntos.\n\nIVANA MOLINA & ASOC. BIENES RAÍCES\nMAT 1048 – CDMDLM',
    beds: 0,
    baths: 0,
    area: '546 m² c/u',
    features: ['Frente al campo', 'Lotes de 546 m²', 'A 250m del asfalto', 'Parquizado con arboleda'],
    coordinates: { x: 48, y: 58 },
    isFeatured: true,
    isMostWanted: true,
  },
  {
    id: 'prop-7',
    transactionType: 'venta',
    title: 'Pablo Ceretti',
    subtitle: 'Terreno de 900 m² con Arboleda Añosa',
    price: 'Consultar Precio',
    priceNumeric: 0,
    location: '20 de Junio, La Matanza',
    streets: 'Pablo Ceretti, entre Gibson y Av. Gorostiaga',
    mercadoLibreLink: 'https://terreno.mercadolibre.com.ar/MLA-1812584553-terreno-en-venta-20-de-junio-900-m2--_JM',
    category: 'terrenos',
    image: '/venta/terrenos/Terreno_Venta_PabloCeretti_20DeJunio_LaMatanza/Ajustes de nitidez y temperatura.webp',
    images: [
      '/venta/terrenos/Terreno_Venta_PabloCeretti_20DeJunio_LaMatanza/Ajustes de nitidez y temperatura.webp',
      '/venta/terrenos/Terreno_Venta_PabloCeretti_20DeJunio_LaMatanza/foto-2.webp',
      '/venta/terrenos/Terreno_Venta_PabloCeretti_20DeJunio_LaMatanza/foto-3.webp',
      '/venta/terrenos/Terreno_Venta_PabloCeretti_20DeJunio_LaMatanza/foto-4.webp'
    ],
    description: 'Terreno en Venta – Pablo Ceretti, 20 de Junio\nUbicación: Calle Pablo Ceretti, entre Gibson y Av. Gorostiaga, 20 de Junio, La Matanza.\n\nExcelente fracción de terreno de aproximadamente 900 m² a la venta. La propiedad se destaca por su entorno sumamente tranquilo y natural, ideal para quienes buscan privacidad, descanso y contacto con la naturaleza.\n\nCaracterísticas principales:\n• Superficie aproximada: 900 m²\n• Hermosa arboleda añosa con variedad de especies, garantizando sombra y un ambiente muy agradable durante todo el año.\n• Posee su respectivo título de propiedad al día.\n\nInformación sobre subdivisión:\n• La subdivisión se encuentra pendiente de realización.\n• El proyecto de subdivisión ya fue evaluado y aprobado por agrimensor, habiéndose verificado que las medidas proyectadas cumplen con las dimensiones mínimas exigidas por la zonificación correspondiente a la zona.\n\nUna opción ideal tanto para vivienda permanente, casa de fin de semana o como proyecto de inversión en una zona de alta tranquilidad y en constante crecimiento.\n\nIVANA MOLINA & ASOC. BIENES RAÍCES\nMAT 1048 – CDMDLM',
    beds: 0,
    baths: 0,
    area: '900 m²',
    features: ['Arboleda añosa', 'Terreno de 900 m²', 'Subdivisión aprobada', 'Excelente entorno natural'],
    coordinates: { x: 50, y: 38 },
    isFeatured: true,
    isMostWanted: true,
  }
];

export const testimonials: Testimonial[] = [
  {
    id: 'test-1',
    name: 'Alexander Sterling',
    role: 'Inversor en Tecnología Financiera',
    text: '“La reserva y el nivel de detalle en su asesoría superaron mis expectativas. Consiguieron una residencia brutalista exclusiva fuera del mercado y concretaron la compra en pocos días con total discreción.”',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    rating: 5,
  },
  {
    id: 'test-2',
    name: 'Dra. Elena Rostova',
    role: 'Coleccionista de Arte y Filántropa',
    text: '“Vila Lumina es una obra de arte y una extensión de mi galería. La luz natural y la amplitud de los espacios son extraordinarias. Su servicio personalizado es clave para adquirir propiedades de verdadero prestigio internacional.”',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
    rating: 5,
  },
  {
    id: 'test-3',
    name: 'Kenji y Sakura Sato',
    role: 'Inversores en Bienes de Lujo',
    text: '“Adquirir el lote Terra Sanctum con planos aprobados fue nuestra mejor decisión del año. Su comprensión del mercado premium y su acompañamiento legal y técnico simplificaron una operación compleja con absoluta seguridad.”',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=200&q=80',
    rating: 5,
  },
];

export const stats: Stat[] = [
  {
    id: 'stat-1',
    label: 'Inversiones Concretadas',
    value: 124,
    suffix: 'M+',
    prefix: '$',
  },
  {
    id: 'stat-2',
    label: 'Clientes Satisfechos',
    value: 85,
    suffix: '',
  },
  {
    id: 'stat-3',
    label: 'Años de Trayectoria',
    value: 12,
    suffix: '+',
  },
  {
    id: 'stat-4',
    label: 'Transacciones Exitosas',
    value: 99.4,
    suffix: '%',
  },
];
