import { Property, Testimonial, Stat } from './types';

export const properties: Property[] = [
  {
    id: 'prop-1',
    transactionType: 'venta',
    title: 'Manuel Antonio Castro',
    subtitle: 'Ante esquina Paso de los Libres',
    price: 'Consultar Precio',
    priceNumeric: 0,
    location: '20 de Junio, La Matanza',
    streets: 'Manuel A. Castro y Paso de los Libres',
    mercadoLibreLink: 'https://terreno.mercadolibre.com.ar/MLA-2627762324-terreno-en-venta-20-de-junio-_JM',
    category: 'terrenos',
    image: '/venta/terrenos/Terreno-Manual-Antonio-Castro-y-1200-PasodeLoslibres--PORTADA--.webp',
    images: [
      '/venta/terrenos/Terreno-Manual-Antonio-Castro-y-1200-PasodeLoslibres--PORTADA--.webp',
      '/venta/terrenos/Terreno-Manual-Antonio-Castro-y-1200-PasodeLoslibres--1--.webp',
      '/venta/terrenos/Terreno-Manual-Antonio-Castro-y-1200-PasodeLoslibres--2--.webp'
    ],
    description: 'Terreno en Venta – Parcela 9 (Ante esquina)\nUbicación: Manuel Castro, 20 de Junio, La Matanza.\n\nExcelente oportunidad de inversión en una de las zonas más buscadas de 20 de Junio. La parcela se encuentra ubicada en ante esquina entre Manuel Castro y Paso de los Libres, a solo una cuadra del asfalto, con un entorno óptimo y vecinos linderos que cuentan principalmente con casas quintas, aportando tranquilidad y buena convivencia.\n\nDimensiones y características:\n• Frente: 27 metros\n• Fondo: 55 metros\n• Superficie total: 1.500 m²\n\nPosee una arboleda frondosa, destacándose varias acacias que brindan una sombra natural ideal para disfrutar del espacio verde. El lote ofrece una superficie amplia y aprovechable para diversos proyectos.\n\nIdeal para vivienda, descanso de fin de semana o inversión a futuro.\n\nIVANA MOLINA & ASOC. BIENES RAÍCES\nMAT 1048\nCDMDLM',
    beds: 0,
    baths: 0,
    area: '1,500 m²',
    features: ['Arboleda Frondosa', 'Zona Residencial (Quintas)', 'A 100m del asfalto', 'Inversión Segura'],
    coordinates: { x: 35, y: 40 },
    isFeatured: true,
    isMostWanted: true,
  },
  {
    id: 'prop-2',
    transactionType: 'venta',
    title: 'Lote en Alejo Castex',
    subtitle: 'Dos terrenos contiguos (3000 m²)',
    price: 'Consultar Precio',
    priceNumeric: 0,
    location: '20 de Junio, La Matanza',
    streets: 'Alejo Castex y Manuel A. Castro',
    mercadoLibreLink: 'https://terreno.mercadolibre.com.ar/MLA-2587214160-dos-terrenos-a-la-venta-20-de-junio-_JM',
    category: 'terrenos',
    image: '/venta/terrenos/Terreno-alejo-castex-portada.webp',
    images: [
      '/venta/terrenos/Terreno-alejo-castex-portada.webp',
      '/venta/terrenos/Terreno-Alejo-Castex-1.webp'
    ],
    description: 'TERRENO 3000 m² ALEJO CASTEX, 20 DE JUNIO, LA MATANZA\n\nSe venden dos terrenos contiguos, cada uno con salida a distintas calles, ofreciendo una ubicación estratégica y múltiple accesibilidad.\n• Terreno 1 con frente a Alejo Castex\n• Terreno 2 con frente a Manuel Castro\n\nAmbos lotes se encuentran parquizados, alambrados y arbolados, ideales para quienes buscan un entorno natural y listo para proyectar.\n\nCada terreno posee:\n• 27,50 metros de frente\n• 55 metros de fondo\n• Superficie total aproximada: 1.512 m² por lote\n\nLa ubicación es excelente: zona tranquila, en pleno centro de 20 de Junio, con cercanía a comercios, transporte y rápido acceso a las principales arterias. Perfectos para proyecto residencial, emprendimiento o inversión.\n\nIVANA MOLINA & ASOC. BIENES RAÍCES\nMAT 1048\nCDMDLM',
    beds: 0,
    baths: 0,
    area: '3,000 m²',
    features: ['Doble Acceso por Calles Diferentes', 'Parquizado y Alambrado', 'Ubicación Estratégica Céntrica', 'Lotes Subdividibles'],
    coordinates: { x: 58, y: 25 },
    isFeatured: true,
    isMostWanted: true,
  },
  {
    id: 'prop-3',
    transactionType: 'venta',
    title: 'Cosquín 1400',
    subtitle: 'Casa Quinta – Terreno de 1.610 m²',
    price: 'Consultar Precio',
    priceNumeric: 0,
    location: '20 de Junio, La Matanza',
    streets: 'Cosquín y Manuel Castro',
    mercadoLibreLink: 'https://casa.mercadolibre.com.ar/MLA-1557210415-casa-quinta-en-venta-20-de-junio-terreno-1610-m2-_JM',
    category: 'casas-quinta',
    image: '/venta/casas-quinta/COSQUIN 1400-Casa Quinta En Ven/COSQUIN 1400-Casa Quinta En Venta- 1.webp',
    images: [
      '/venta/casas-quinta/COSQUIN 1400-Casa Quinta En Ven/COSQUIN 1400-Casa Quinta En Venta- 1.webp',
      '/venta/casas-quinta/COSQUIN 1400-Casa Quinta En Ven/COSQUIN 1400-Casa Quinta En Vent-2.webp',
      '/venta/casas-quinta/COSQUIN 1400-Casa Quinta En Ven/COSQUIN 1400-Casa Quinta En Vent-3.webp',
      '/venta/casas-quinta/COSQUIN 1400-Casa Quinta En Ven/COSQUIN 1400-Casa Quinta En Vent-4.webp',
      '/venta/casas-quinta/COSQUIN 1400-Casa Quinta En Ven/COSQUIN 1400-Casa Quinta En Vent-5.webp',
      '/venta/casas-quinta/COSQUIN 1400-Casa Quinta En Ven/COSQUIN 1400-Casa Quinta En Vent-6.webp',
      '/venta/casas-quinta/COSQUIN 1400-Casa Quinta En Ven/COSQUIN 1400-Casa Quinta En Vent-7.webp'
    ],
    description: 'Casa Quinta en Venta – 20 de Junio, La Matanza\nUbicación: Cosquín y Manuel Castro (casi en el ingreso a la localidad).\n\nEsta propiedad ofrece una ubicación privilegiada dentro de un entorno tranquilo y natural. Sobre un terreno de 1.610 m² con una particular forma de diamante y rodeado de árboles añosos, se desarrolla una cálida casa con un diseño funcional y excelente iluminación natural.\n\nLa vivienda cuenta con una cocina integrada a un amplio living-comedor, un espacio abierto y luminoso ideal para disfrutar en familia. Un pasillo distribuidor conecta con un baño completo y la habitación principal en planta baja. En la planta alta se encuentra una segunda habitación que amplía las posibilidades de uso.\n\nEn el exterior, la propiedad dispone de un baño adicional, un cuarto de herramientas y una pileta de aproximadamente 9 x 4 metros, rodeada de verde y total privacidad, ideal para disfrutar de los días de descanso. Una opción perfecta para quienes buscan naturaleza, comodidad y una excelente ubicación a pocos minutos de la ciudad.\n\n*Las imágenes han sido optimizadas mediante herramientas de inteligencia artificial con el único fin de mejorar la calidad visual (iluminación, nitidez) y eliminar elementos circunstanciales que no aportan a la lectura del espacio. No se han modificado dimensiones, distribución ni características estructurales del inmueble.*\n\nMOLINA IVANA & ASOC. BIENES RAÍCES\nMAT 1048 – COLEGIO DE MARTILLEROS DE LA MATANZA',
    beds: 2,
    baths: 2,
    area: '1.610 m²',
    features: ['Pileta de 9x4 m', 'Terreno de 1.610 m²', 'Arboleda Añosa', 'Excelente Ubicación en Esquina'],
    coordinates: { x: 45, y: 55 },
    isFeatured: true,
    isMostWanted: true,
  },
  {
    id: 'prop-4',
    transactionType: 'venta',
    title: 'Castañeda y Cosquín',
    subtitle: 'Casa Quinta con Piscina – Terreno de 1.500 m²',
    price: 'Consultar Precio',
    priceNumeric: 0,
    location: '20 de Junio, La Matanza',
    streets: 'Castañeda y Cosquín',
    mercadoLibreLink: 'https://casa.mercadolibre.com.ar/MLA-2429890272-casa-quinta-en-venta-en-20-de-junio-con-piscina-terreno-1500-m2-_JM',
    category: 'casas-quinta',
    image: '/venta/casas-quinta/CasaQuinta_Venta_20DeJunio_Piscina_1500m2/1.webp',
    images: [
      '/venta/casas-quinta/CasaQuinta_Venta_20DeJunio_Piscina_1500m2/1.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_20DeJunio_Piscina_1500m2/2.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_20DeJunio_Piscina_1500m2/3.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_20DeJunio_Piscina_1500m2/4.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_20DeJunio_Piscina_1500m2/5.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_20DeJunio_Piscina_1500m2/6.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_20DeJunio_Piscina_1500m2/8.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_20DeJunio_Piscina_1500m2/9.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_20DeJunio_Piscina_1500m2/13.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_20DeJunio_Piscina_1500m2/14.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_20DeJunio_Piscina_1500m2/15.webp'
    ],
    description: 'Casa Quinta en Venta – 20 de Junio, La Matanza\nUbicación: Castañeda esquina Cosquín, 20 de Junio, La Matanza.\n\nUbicada en una excelente esquina con acceso por asfalto, esta cálida propiedad se desarrolla sobre un importante terreno parquizado de 1.500 m² con cerco perimetral y una añosa arboleda que brinda una agradable sombra natural.\n\nDimensiones y características principales:\n• Superficie del terreno: 1.500 m²\n• Superficie cubierta: 144,87 m²\n• Acceso por hall exterior y garaje techado.\n\nDistribución interior:\n• Amplio living-comedor.\n• Cocina independiente.\n• 3 habitaciones.\n• 2 baños completos.\n\nEspacio exterior y jardín:\n• Gran piscina de natación de aproximadamente 9,50 x 4,90 metros.\n• Quincho cerrado equipado con cocina, parrilla, horno de barro y un baño completo adicional.\n• Jardín completamente parquizado y arbolado.\n\nInformación destacada:\n• ¡Apto crédito hipotecario! (Posee planos registrados, consultar detalles).\n• IMPORTANTE: Se toma propiedad en parte de pago en las localidades de San Bernardo o Mar del Plata.\n\nIVANA MOLINA & ASOC. BIENES RAÍCES\nMAT 1048 – CDMDLM',
    beds: 3,
    baths: 3,
    area: '1.500 m²',
    features: ['Piscina 9.5x4.9 m', 'Terreno de 1.500 m²', 'Apta Crédito Hipotecario', 'Quincho con Horno de Barro'],
    coordinates: { x: 40, y: 48 },
    isFeatured: true,
    isMostWanted: true,
  },
  {
    id: 'prop-5',
    transactionType: 'venta',
    title: 'Cosquín 1120',
    subtitle: 'Casa Quinta Apto Crédito – Terreno de 1.347 m²',
    price: 'Consultar Precio',
    priceNumeric: 0,
    location: '20 de Junio, La Matanza',
    streets: 'Cosquín 1120',
    mercadoLibreLink: 'https://inmueble.mercadolibre.com.ar/MLA-2003958026-casa-quinta-en-venta-terreno-1347-m2-apto-credito-_JM',
    category: 'casas-quinta',
    image: '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/1.webp',
    images: [
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/1.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/2.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/3.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/4.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/5.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/6.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/7.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/8.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/9.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/10.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/11.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/12.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/13.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/14.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/15.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/16.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/17.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/18.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/19.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/20.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/21.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/22.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/23.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/24.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/25.webp',
      '/venta/casas-quinta/CasaQuinta_Venta_Cosquin1120_1347m2_AptoCredito/26.webp'
    ],
    description: 'Casa Quinta en Venta – 20 de Junio, La Matanza\nUbicación: Cosquín 1120, 20 de Junio, La Matanza.\n\nExcelente propiedad en venta que se destaca por su gran nivel de comodidad, excelente ubicación y sistema de riego instalado en todo el terreno.\n\nDimensiones y características principales:\n• Superficie del terreno: 1.347 m²\n• Pileta de 8 x 4 metros con solárium de 3 x 3 metros.\n• Cochera semicubierta y garaje cubierto con capacidad para 3 autos.\n\nDistribución interior:\n• 3 habitaciones de cómodas dimensiones (4 x 4 metros), una de ellas en suite.\n• Cocina, comedor y living integrados en un amplio espacio funcional.\n• 2 baños completos en total para el interior.\n• 1 toilette de recepción.\n\nEspacio exterior:\n• Amplia galería con parrilla.\n• Baño exterior exclusivo para el área de la pileta.\n• Gran parque parquizado.\n\nInformación y condiciones destacadas:\n• ¡Apta crédito hipotecario!\n• Se toma departamento en Zona Oeste o Capital Federal en parte de pago.\n• Se acepta permuta de mayor valor en las siguientes zonas: Castelar, Ituzaingó y Parque Leloir.\n\nMOLINA IVANA & ASOC. BIENES RAÍCES\nMAT 1048 – CDMDLM',
    beds: 3,
    baths: 4,
    area: '1.347 m²',
    features: ['Pileta 8x4m + Solárium', 'Lote de 1.347 m²', 'Apta Crédito Hipotecario', 'Cochera para 3 Autos', 'Riego por Aspersión'],
    coordinates: { x: 42, y: 52 },
    isFeatured: true,
    isMostWanted: true,
  },
  {
    id: 'prop-6',
    transactionType: 'venta',
    title: 'Juan Casacuberta',
    subtitle: 'Terrenos en Venta (Lotes 18 y 19) – 546 m² c/u',
    price: 'Consultar Precio',
    priceNumeric: 0,
    location: '20 de Junio, La Matanza',
    streets: 'Juan Casacuberta, entre Cóndor y Corona',
    mercadoLibreLink: 'https://terreno.mercadolibre.com.ar/MLA-2704874184-terrenos-en-venta-546-metros-20-de-junio--_JM',
    category: 'terrenos',
    image: '/venta/terrenos/Terreno_Venta_JuanCasacuberta_20DeJunio_LaMatanza/PORTADA-1.webp',
    images: [
      '/venta/terrenos/Terreno_Venta_JuanCasacuberta_20DeJunio_LaMatanza/PORTADA-1.webp',
      '/venta/terrenos/Terreno_Venta_JuanCasacuberta_20DeJunio_LaMatanza/foto-2.webp'
    ],
    description: 'Terrenos en Venta – Juan Casacuberta, 20 de Junio\nUbicación: Calle Juan Casacuberta, entre Cóndor y Corona, localidad de 20 de Junio, La Matanza.\n\nExcelente oportunidad de adquisición de lotes individuales o en conjunto. Se trata de dos terrenos contiguos (Lotes 18 y 19) parquizados, con una hermosa arboleda natural y listos para construir.\n\nCaracterísticas y dimensiones (cada lote):\n• Frente: 13 metros\n• Fondo: 42 metros\n• Superficie total: 546 m² por lote\n\nUbicación y entorno:\n• A solo 2 cuadras y media del asfalto.\n• Ubicados frente al campo, en una zona sumamente tranquila y rodeada de naturaleza.\n• Excelente entorno con gran potencial de desarrollo y crecimiento.\n\nInformación comercial:\n• Los lotes se venden por separado.\n• El valor publicado es individual (por cada uno).\n• Se escuchan ofertas por la compra de ambos lotes juntos.\n\nIVANA MOLINA & ASOC. BIENES RAÍCES\nMAT 1048 – CDMDLM',
    beds: 0,
    baths: 0,
    area: '546 m² c/u',
    features: ['Frente al campo', 'Lotes de 546 m²', 'A 250m del asfalto', 'Parquizado con arboleda'],
    coordinates: { x: 48, y: 58 },
    isFeatured: true,
    isMostWanted: true,
  },
  {
    id: 'prop-7',
    transactionType: 'venta',
    title: 'Pablo Ceretti',
    subtitle: 'Terreno de 900 m² con Arboleda Añosa',
    price: 'Consultar Precio',
    priceNumeric: 0,
    location: '20 de Junio, La Matanza',
    streets: 'Pablo Ceretti, entre Gibson y Av. Gorostiaga',
    mercadoLibreLink: 'https://terreno.mercadolibre.com.ar/MLA-1812584553-terreno-en-venta-20-de-junio-900-m2--_JM',
    category: 'terrenos',
    image: '/venta/terrenos/Terreno_Venta_PabloCeretti_20DeJunio_LaMatanza/Ajustes de nitidez y temperatura.webp',
    images: [
      '/venta/terrenos/Terreno_Venta_PabloCeretti_20DeJunio_LaMatanza/Ajustes de nitidez y temperatura.webp',
      '/venta/terrenos/Terreno_Venta_PabloCeretti_20DeJunio_LaMatanza/foto-2.webp',
      '/venta/terrenos/Terreno_Venta_PabloCeretti_20DeJunio_LaMatanza/foto-3.webp',
      '/venta/terrenos/Terreno_Venta_PabloCeretti_20DeJunio_LaMatanza/foto-4.webp'
    ],
    description: 'Terreno en Venta – Pablo Ceretti, 20 de Junio\nUbicación: Calle Pablo Ceretti, entre Gibson y Av. Gorostiaga, 20 de Junio, La Matanza.\n\nExcelente fracción de terreno de aproximadamente 900 m² a la venta. La propiedad se destaca por su entorno sumamente tranquilo y natural, ideal para quienes buscan privacidad, descanso y contacto con la naturaleza.\n\nCaracterísticas principales:\n• Superficie aproximada: 900 m²\n• Hermosa arboleda añosa con variedad de especies, garantizando sombra y un ambiente muy agradable durante todo el año.\n• Posee su respectivo título de propiedad al día.\n\nInformación sobre subdivisión:\n• La subdivisión se encuentra pendiente de realización.\n• El proyecto de subdivisión ya fue evaluado y aprobado por agrimensor, habiéndose verificado que las medidas proyectadas cumplen con las dimensiones mínimas exigidas por la zonificación correspondiente a la zona.\n\nUna opción ideal tanto para vivienda permanente, casa de fin de semana o como proyecto de inversión en una zona de alta tranquilidad y en constante crecimiento.\n\nIVANA MOLINA & ASOC. BIENES RAÍCES\nMAT 1048 – CDMDLM',
    beds: 0,
    baths: 0,
    area: '900 m²',
    features: ['Arboleda añosa', 'Terreno de 900 m²', 'Subdivisión aprobada', 'Excelente entorno natural'],
    coordinates: { x: 50, y: 38 },
    isFeatured: true,
    isMostWanted: true,
  },
  {
    id: 'prop-8',
    transactionType: 'venta',
    title: 'Casa Quinta En Venta',
    subtitle: 'Terreno 2800 M2 - 20 De Junio',
    price: 'Consultar Precio',
    priceNumeric: 0,
    location: '20 de Junio, La Matanza',
    streets: 'California 5900',
    mercadoLibreLink: 'https://casa.mercadolibre.com.ar/MLA-3337509402-casa-quinta-en-venta-terreno-2800-m2-20-de-junio-_JM',
    category: 'casas-quinta',
    image: '/venta/casas-quinta/casa-quinta-california-5900/1.webp',
    images: [
      '/venta/casas-quinta/casa-quinta-california-5900/1.webp',
      '/venta/casas-quinta/casa-quinta-california-5900/2.webp',
      '/venta/casas-quinta/casa-quinta-california-5900/3.webp',
      '/venta/casas-quinta/casa-quinta-california-5900/4.webp',
      '/venta/casas-quinta/casa-quinta-california-5900/5.webp',
      '/venta/casas-quinta/casa-quinta-california-5900/6.webp',
      '/venta/casas-quinta/casa-quinta-california-5900/7.webp',
      '/venta/casas-quinta/casa-quinta-california-5900/8.webp',
      '/venta/casas-quinta/casa-quinta-california-5900/9.webp',
      '/venta/casas-quinta/casa-quinta-california-5900/10.webp',
      '/venta/casas-quinta/casa-quinta-california-5900/11.webp',
      '/venta/casas-quinta/casa-quinta-california-5900/12.webp',
      '/venta/casas-quinta/casa-quinta-california-5900/13.webp',
      '/venta/casas-quinta/casa-quinta-california-5900/14.webp',
      '/venta/casas-quinta/casa-quinta-california-5900/15.webp'
    ],
    description: 'Casa Quinta en Venta sobre amplio lote de 2.800 m² ubicada en California 5900, 20 de Junio, La Matanza.\n\nLa propiedad se desarrolla en una sola planta y cuenta con un luminoso living-comedor integrado. Dispone de una cocina amplia y funcional, dos dormitorios, baño completo en el interior y lavadero cubierto. Además, posee un proyecto de ampliación en planta alta que aporta gran potencial de crecimiento y desarrollo.\n\nEn el exterior, se destaca un gran parque arbolado con abundante sombra natural. La propiedad cuenta con dos piletas y un pintoresco quincho con techo de paja, el cual se complementa con un baño exterior para mayor comodidad.\n\nCaracterísticas destacadas:\n• Terreno de 2.800 m²\n• Acceso por calle de ripio\n• Excelente entorno natural\n• Amplio parque y arboleda\n• Quincho y dos piletas\n\nIVANA MOLINA & ASOC. BIENES RAÍCES\nMAT 1048\nCOLEGIO DE MARTILLEROS DE LA MATANZA',
    beds: 2,
    baths: 2,
    area: '2.800 m²',
    features: ['Amplio parque y arboleda', 'Quincho y dos piletas', 'Proyecto de ampliación', 'Excelente entorno natural'],
    coordinates: { x: 50, y: 50 },
    isFeatured: true,
    isMostWanted: false,
  },
  {
    id: 'prop-9',
    transactionType: 'alquiler',
    title: 'Casa Quinta En Alquiler Permanente',
    subtitle: 'Destino Vivienda - 20 De Junio',
    price: 'Consultar Precio',
    priceNumeric: 0,
    location: '20 de Junio, La Matanza',
    streets: 'California 5900',
    mercadoLibreLink: 'https://casa.mercadolibre.com.ar/MLA-3219356036-casa-quinta-en-alquiler-destino-vivienda-20-de-junio-_JM',
    category: 'casas-quinta',
    image: '/venta/casas-quinta/casa-quinta-california-5900/1.webp',
    images: [
      '/venta/casas-quinta/casa-quinta-california-5900/1.webp',
      '/venta/casas-quinta/casa-quinta-california-5900/2.webp',
      '/venta/casas-quinta/casa-quinta-california-5900/3.webp',
      '/venta/casas-quinta/casa-quinta-california-5900/4.webp',
      '/venta/casas-quinta/casa-quinta-california-5900/5.webp',
      '/venta/casas-quinta/casa-quinta-california-5900/6.webp',
      '/venta/casas-quinta/casa-quinta-california-5900/7.webp',
      '/venta/casas-quinta/casa-quinta-california-5900/8.webp',
      '/venta/casas-quinta/casa-quinta-california-5900/9.webp',
      '/venta/casas-quinta/casa-quinta-california-5900/10.webp',
      '/venta/casas-quinta/casa-quinta-california-5900/11.webp',
      '/venta/casas-quinta/casa-quinta-california-5900/12.webp',
      '/venta/casas-quinta/casa-quinta-california-5900/13.webp',
      '/venta/casas-quinta/casa-quinta-california-5900/14.webp',
      '/venta/casas-quinta/casa-quinta-california-5900/15.webp'
    ],
    description: 'Casa Quinta en Alquiler Permanente (Destino Vivienda) ubicada en California 5900, 20 de Junio, La Matanza.\n\nIdeal para quienes buscan comodidad y espacios al aire libre en un entorno tranquilo y rodeado de naturaleza. La propiedad se desarrolla en una sola planta y cuenta con un amplio y luminoso living-comedor integrado, equipado con salamandra y aire acondicionado frío/calor, generando un ambiente confortable durante todo el año.\n\nDispone de una cocina amplia y funcional, dos dormitorios (uno de ellos con aire acondicionado solo frío) y un baño completo en el interior de la vivienda. Además, posee un lavadero cubierto que brinda practicidad para las tareas diarias.\n\nEn el exterior se destaca un amplio parque con gran arboleda, aportando sombra natural y un entorno muy agradable. La propiedad cuenta con dos piletas y un quincho con techo de paja, ideal para reuniones y momentos de recreación, que incluye un baño exterior para mayor comodidad.\n\nUna propiedad que combina confort interior con amplios espacios verdes, perfecta para disfrutar de la tranquilidad como vivienda permanente.\n\nIVANA MOLINA & ASOC. BIENES RAÍCES\nMAT 1048\nCOLEGIO DE MARTILLEROS DE LA MATANZA',
    beds: 2,
    baths: 2,
    area: '2.800 m²',
    features: ['Parque con gran arboleda', 'Quincho y dos piletas', 'Salamandra y Aire Acondicionado', 'Alquiler Permanente'],
    coordinates: { x: 50, y: 50 },
    isFeatured: true,
    isMostWanted: false,
  },
  {
    id: 'prop-10',
    transactionType: 'venta',
    title: 'Propiedad de 6 Ambientes',
    subtitle: 'Intendente Gabriel Larralde 2127, Caseros',
    price: 'Consultar Precio',
    priceNumeric: 0,
    location: 'Caseros, Tres de Febrero',
    streets: 'Int. Gabriel Larralde 2127',
    mercadoLibreLink: '',
    category: 'casas',
    image: '/venta/casas-quinta/propiedad-de-6-ambientes-caseros/1.webp',
    images: [
      '/venta/casas-quinta/propiedad-de-6-ambientes-caseros/1.webp',
      '/venta/casas-quinta/propiedad-de-6-ambientes-caseros/2.webp',
      '/venta/casas-quinta/propiedad-de-6-ambientes-caseros/3.webp',
      '/venta/casas-quinta/propiedad-de-6-ambientes-caseros/4.webp',
      '/venta/casas-quinta/propiedad-de-6-ambientes-caseros/5.webp',
      '/venta/casas-quinta/propiedad-de-6-ambientes-caseros/6.webp',
      '/venta/casas-quinta/propiedad-de-6-ambientes-caseros/7.webp',
      '/venta/casas-quinta/propiedad-de-6-ambientes-caseros/8.webp',
      '/venta/casas-quinta/propiedad-de-6-ambientes-caseros/9.webp',
      '/venta/casas-quinta/propiedad-de-6-ambientes-caseros/10.webp',
      '/venta/casas-quinta/propiedad-de-6-ambientes-caseros/11.webp',
      '/venta/casas-quinta/propiedad-de-6-ambientes-caseros/12.webp',
      '/venta/casas-quinta/propiedad-de-6-ambientes-caseros/13.webp',
      '/venta/casas-quinta/propiedad-de-6-ambientes-caseros/14.webp',
      '/venta/casas-quinta/propiedad-de-6-ambientes-caseros/15.webp',
      '/venta/casas-quinta/propiedad-de-6-ambientes-caseros/16.webp',
      '/venta/casas-quinta/propiedad-de-6-ambientes-caseros/17.webp',
      '/venta/casas-quinta/propiedad-de-6-ambientes-caseros/18.webp',
      '/venta/casas-quinta/propiedad-de-6-ambientes-caseros/19.webp',
      '/venta/casas-quinta/propiedad-de-6-ambientes-caseros/20.webp',
      '/venta/casas-quinta/propiedad-de-6-ambientes-caseros/21.webp'
    ],
    description: 'Excelente propiedad de 6 ambientes en venta, desarrollada sobre un lote de 290 m² con aproximadamente 120 m² cubiertos, ubicada en Intendente Gabriel Larralde 2127, Caseros.\n\nLa vivienda destaca por su comodidad y distribución funcional. Cuenta con un amplio living-comedor, cocina, tres dormitorios y tres baños. Además, dispone de un lavadero, un cuarto de guardado y cochera con capacidad para dos vehículos. Los detalles de categoría incluyen calefacción central por radiadores, elegantes pisos de pinotea plastificada y pisos flotantes en los dormitorios.\n\nEn el exterior, la propiedad ofrece un espacio ideal para disfrutar al aire libre, contando con una pileta equipada con sistema completo de bomba y filtrado.\n\nUna excelente opción para quienes buscan amplitud, confort y una inmejorable ubicación.\n\nIVANA MOLINA & ASOC. BIENES RAÍCES\nMAT 1048\nCOLEGIO DE MARTILLEROS DE LA MATANZA',
    beds: 3,
    baths: 3,
    area: '290 m²',
    features: ['Pileta con bomba y filtrado', 'Calefacción central', 'Cochera para 2', 'Pisos de pinotea'],
    coordinates: { x: 55, y: 45 },
    isFeatured: true,
    isMostWanted: false,
  },
  {
    id: 'prop-11',
    transactionType: 'venta',
    title: 'Casa Quinta Con Pileta y Quincho',
    subtitle: 'Cevallos, 20 De Junio',
    price: 'Consultar Precio',
    priceNumeric: 0,
    location: '20 de Junio, La Matanza',
    streets: 'Cevallos',
    mercadoLibreLink: 'https://casa.mercadolibre.com.ar/MLA-3531537360-casa-quinta-en-venta-en-20-de-junio-_JM',
    category: 'casas-quinta',
    image: '/venta/casas-quinta/casa-quinta-con-pileta-y-quincho-cevallos/1.webp',
    images: [
      '/venta/casas-quinta/casa-quinta-con-pileta-y-quincho-cevallos/1.webp',
      '/venta/casas-quinta/casa-quinta-con-pileta-y-quincho-cevallos/2.webp',
      '/venta/casas-quinta/casa-quinta-con-pileta-y-quincho-cevallos/3.webp',
      '/venta/casas-quinta/casa-quinta-con-pileta-y-quincho-cevallos/4.webp',
      '/venta/casas-quinta/casa-quinta-con-pileta-y-quincho-cevallos/5.webp',
      '/venta/casas-quinta/casa-quinta-con-pileta-y-quincho-cevallos/6.webp',
      '/venta/casas-quinta/casa-quinta-con-pileta-y-quincho-cevallos/7.webp',
      '/venta/casas-quinta/casa-quinta-con-pileta-y-quincho-cevallos/9.webp',
      '/venta/casas-quinta/casa-quinta-con-pileta-y-quincho-cevallos/10.webp',
      '/venta/casas-quinta/casa-quinta-con-pileta-y-quincho-cevallos/11.webp',
      '/venta/casas-quinta/casa-quinta-con-pileta-y-quincho-cevallos/12.webp',
      '/venta/casas-quinta/casa-quinta-con-pileta-y-quincho-cevallos/13.webp',
      '/venta/casas-quinta/casa-quinta-con-pileta-y-quincho-cevallos/14.webp',
      '/venta/casas-quinta/casa-quinta-con-pileta-y-quincho-cevallos/15.webp'
    ],
    description: 'Casa Quinta en Venta – ¡Con pileta, quincho y excelente ubicación!\n\nUbicada en calle Cevallos, 20 de Junio, La Matanza.\n\nHermosa casa quinta desarrollada sobre un terreno de 395 m², ubicada a tan solo 5/10 metros del asfalto, en una zona tranquila y de fácil acceso. La propiedad cuenta con 80 m² cubiertos y una pintoresca galería al frente, ideal para disfrutar de las tardes al aire libre.\n\nEn su interior presenta un amplio y luminoso ambiente en "L" que integra cocina, comedor y living, destacando sus techos de pino que aportan gran calidez y estilo. Dispone de tres cómodas habitaciones y un baño completo.\n\nEn el exterior se destaca una pileta de fibra de vidrio de aproximadamente 6 x 3 metros, perfecta para disfrutar del verano. Además, cuenta con un amplio quincho cerrado de 10 x 3,20 metros (que también puede utilizarse como garage), equipado con baño y una pequeña mesada con bacha lavaplatos.\n\nLa propiedad posee bomba sumergible y todas las comodidades necesarias para disfrutarla tanto como vivienda permanente o casa de fin de semana.\n\nATENCIÓN: Se acepta permuta por propiedad en CABA o Mar del Plata.\n\nIVANA MOLINA & ASOC. BIENES RAÍCES\nMAT 1048\nCOLEGIO DE MARTILLEROS DE LA MATANZA',
    beds: 3,
    baths: 2,
    area: '395 m²',
    features: ['Pileta de 6x3', 'Quincho cerrado/Garage', 'Apto permuta CABA/MDQ', 'A 10m del asfalto'],
    coordinates: { x: 45, y: 55 },
    isFeatured: true,
    isMostWanted: false,
  },
  {
    id: 'prop-12',
    transactionType: 'alquiler',
    title: 'Casa Quinta En Alquiler Permanente',
    subtitle: 'Cosquín 194, 20 De Junio',
    price: 'Consultar Precio',
    priceNumeric: 0,
    location: '20 de Junio, La Matanza',
    streets: 'Cosquín 194',
    mercadoLibreLink: 'https://casa.mercadolibre.com.ar/MLA-3531940376-casa-quinta-en-alquiler-destino-vivienda-permanente-20-de-junio-_JM#',
    category: 'casas-quinta',
    image: '/venta/casas-quinta/casa-quinta-en-alquiler-permanente-cosquin-194/1.webp',
    images: [
      '/venta/casas-quinta/casa-quinta-en-alquiler-permanente-cosquin-194/1.webp',
      '/venta/casas-quinta/casa-quinta-en-alquiler-permanente-cosquin-194/2.webp',
      '/venta/casas-quinta/casa-quinta-en-alquiler-permanente-cosquin-194/3.webp',
      '/venta/casas-quinta/casa-quinta-en-alquiler-permanente-cosquin-194/4.webp',
      '/venta/casas-quinta/casa-quinta-en-alquiler-permanente-cosquin-194/5.webp',
      '/venta/casas-quinta/casa-quinta-en-alquiler-permanente-cosquin-194/6.webp',
      '/venta/casas-quinta/casa-quinta-en-alquiler-permanente-cosquin-194/7.webp',
      '/venta/casas-quinta/casa-quinta-en-alquiler-permanente-cosquin-194/8.webp',
      '/venta/casas-quinta/casa-quinta-en-alquiler-permanente-cosquin-194/9.webp',
      '/venta/casas-quinta/casa-quinta-en-alquiler-permanente-cosquin-194/10.webp',
      '/venta/casas-quinta/casa-quinta-en-alquiler-permanente-cosquin-194/11.webp',
      '/venta/casas-quinta/casa-quinta-en-alquiler-permanente-cosquin-194/12.webp',
      '/venta/casas-quinta/casa-quinta-en-alquiler-permanente-cosquin-194/13.webp',
      '/venta/casas-quinta/casa-quinta-en-alquiler-permanente-cosquin-194/14.webp',
      '/venta/casas-quinta/casa-quinta-en-alquiler-permanente-cosquin-194/15.webp',
      '/venta/casas-quinta/casa-quinta-en-alquiler-permanente-cosquin-194/16.webp',
      '/venta/casas-quinta/casa-quinta-en-alquiler-permanente-cosquin-194/17.webp',
      '/venta/casas-quinta/casa-quinta-en-alquiler-permanente-cosquin-194/18.webp',
      '/venta/casas-quinta/casa-quinta-en-alquiler-permanente-cosquin-194/19.webp',
      '/venta/casas-quinta/casa-quinta-en-alquiler-permanente-cosquin-194/20.webp',
      '/venta/casas-quinta/casa-quinta-en-alquiler-permanente-cosquin-194/21.webp',
      '/venta/casas-quinta/casa-quinta-en-alquiler-permanente-cosquin-194/22.webp'
    ],
    description: 'Exclusiva Casa Quinta de estilo campo colonial en Alquiler Permanente, desarrollada sobre un amplio lote de 1.500 m². Ubicada en calle Cosquín 194, en un entorno residencial tranquilo y rodeado de naturaleza en 20 de Junio, La Matanza.\n\nLa propiedad se desarrolla íntegramente en una sola planta, ofreciendo comodidad, amplitud y excelente funcionalidad. Cuenta con tres dormitorios, destacándose la suite principal con vestidor e hidromasaje, además de dos baños completos.\n\nEl sector social dispone de un luminoso living-comedor de generosas dimensiones con excelente ingreso de luz natural, conectado a una cocina independiente equipada con isla/desayunador y un amplio espacio de guardado. En el área de servicios se encuentra un lavadero independiente con salida directa al exterior.\n\nComo gran diferencial, ofrece un espacioso quincho cerrado con parrilla, ideal para reuniones familiares y sociales, con vista abierta al parque. En el exterior se destaca su gran jardín parquizado y arbolado, acompañado por una piscina climatizada con solárium para disfrutar durante todo el año.\n\nCaracterísticas y comodidades adicionales:\n• Terreno de 1.500 m² totalmente cercado\n• Cochera semicubierta para dos vehículos\n• Altillo, porch y hall de acceso\n• Acceso por calle asfaltada\n\n*Importante: El galpón existente en el predio no forma parte del alquiler, quedando cerrado y sin uso.*\n\nUna propiedad ideal para quienes buscan amplitud, calidad constructiva y contacto con la naturaleza.\n\nIVANA MOLINA & ASOC. BIENES RAÍCES\nMAT 1048\nCOLEGIO DE MARTILLEROS DE LA MATANZA',
    beds: 3,
    baths: 2,
    area: '1.500 m²',
    features: ['Piscina Climatizada', 'Quincho cerrado', 'Suite con Hidromasaje', 'Estilo campo colonial'],
    coordinates: { x: 45, y: 55 },
    isFeatured: true,
    isMostWanted: false,
  },
  {
    id: 'prop-13',
    transactionType: 'venta',
    title: 'La Rosalía Quinta',
    subtitle: 'Espectacular Quinta 3.251 m² – Casa Principal + Depto. Independiente Alquilado',
    price: 'Consultar Precio',
    priceNumeric: 0,
    location: '20 de Junio, La Matanza',
    streets: 'Copahue esq. Manuel Rico',
    mercadoLibreLink: '',
    category: 'casas-quinta',
    image: '/venta/casas-quinta/la-rosalia-simona/1.webp',
    images: [
      '/venta/casas-quinta/la-rosalia-simona/1.webp',
      '/venta/casas-quinta/la-rosalia-simona/2.webp',
      '/venta/casas-quinta/la-rosalia-simona/2 (1).webp',
      '/venta/casas-quinta/la-rosalia-simona/3.webp',
      '/venta/casas-quinta/la-rosalia-simona/4.webp',
      '/venta/casas-quinta/la-rosalia-simona/5.webp',
      '/venta/casas-quinta/la-rosalia-simona/6.webp',
      '/venta/casas-quinta/la-rosalia-simona/7.webp',
      '/venta/casas-quinta/la-rosalia-simona/8.webp',
      '/venta/casas-quinta/la-rosalia-simona/9.webp',
      '/venta/casas-quinta/la-rosalia-simona/9 (1).webp',
      '/venta/casas-quinta/la-rosalia-simona/10.webp',
      '/venta/casas-quinta/la-rosalia-simona/11.webp',
      '/venta/casas-quinta/la-rosalia-simona/12.webp',
      '/venta/casas-quinta/la-rosalia-simona/13.webp',
      '/venta/casas-quinta/la-rosalia-simona/13 (1).webp',
      '/venta/casas-quinta/la-rosalia-simona/14.webp',
      '/venta/casas-quinta/la-rosalia-simona/15.webp',
      '/venta/casas-quinta/la-rosalia-simona/16.webp',
      '/venta/casas-quinta/la-rosalia-simona/17.webp',
      '/venta/casas-quinta/la-rosalia-simona/18.webp',
      '/venta/casas-quinta/la-rosalia-simona/19.webp',
      '/venta/casas-quinta/la-rosalia-simona/20.webp',
      '/venta/casas-quinta/la-rosalia-simona/21.webp',
      '/venta/casas-quinta/la-rosalia-simona/22.webp',
      '/venta/casas-quinta/la-rosalia-simona/23.webp',
      '/venta/casas-quinta/la-rosalia-simona/24.webp',
      '/venta/casas-quinta/la-rosalia-simona/25.webp',
      '/venta/casas-quinta/la-rosalia-simona/26.webp',
      '/venta/casas-quinta/la-rosalia-simona/27.webp',
      '/venta/casas-quinta/la-rosalia-simona/28.webp',
      '/venta/casas-quinta/la-rosalia-simona/29.webp',
      '/venta/casas-quinta/la-rosalia-simona/30.webp',
      '/venta/casas-quinta/la-rosalia-simona/31.webp',
      '/venta/casas-quinta/la-rosalia-simona/32.webp',
      '/venta/casas-quinta/la-rosalia-simona/33.webp'
    ],
    description: '¡Una oportunidad única en la exclusiva y tranquila zona de 20 de Junio, La Matanza! Presentamos esta magnífica propiedad residencial emplazada sobre un imponente lote en esquina de 3.251 m² (esquina Copahue y Manuel Rico), que destaca no solo por sus dimensiones y calidad constructiva, sino por su enorme potencial comercial y de subdivisión.\n\nLa propiedad cuenta con una superficie total edificada de 200 m², distribuidos estratégicamente en dos construcciones completamente independientes, ideal para albergar a dos familias, disfrutar de una casa de fin de semana o explotar un negocio de doble renta.\n\n1. CASA PRINCIPAL (Confort y Naturaleza):\nUn hogar cálido y funcional que dispone de un amplio y luminoso living comedor equipado con una hermosa salamandra, ideal para el invierno. Cuenta con cocina comedor diario, un baño completo y 3 cómodas habitaciones (la principal con placard empotrado).\nEl área exterior es un verdadero oasis: un espectacular parque parquizado y completamente iluminado, sector de juegos infantiles para los más chicos, y un espacioso quincho con parrilla. En el otro extremo del jardín, un exclusivo living de exterior diseñado para el relax ofrece una vista inmejorable a la gran piscina de fibra de vidrio.\n\n2. DEPARTAMENTO INDEPENDIENTE (Rentabilidad Inmediata):\nUbicado al otro extremo del lote, sobre la calle Copahue, se encuentra un moderno departamento de 2 habitaciones con cocina, comedor y living integrados en un ambiente amplio y luminoso. Cuenta con su propio ingreso independiente, perforación de agua, medidor de luz individual y su propia piscina de fibra de vidrio.\nNota para inversores: Actualmente se encuentra percibiendo renta con contrato vigente hasta septiembre de 2026 inclusive.\n\n¡GRAN POTENCIAL DE SUBDIVISIÓN!\nLa propiedad cuenta actualmente con el trámite de subdivisión en proceso (con número de expediente vigente). El proyecto contempla la separación legal del departamento menor en un lote propio de 900 m², permitiendo al futuro comprador venderlo de forma individual para recuperar inversión rápida, o bien conservar ambas unidades de forma totalmente independiente para maximizar la renta mensual.\n\nFICHA TÉCNICA:\n• Ubicación: Copahue esq. Manuel Rico, 20 de Junio, La Matanza.\n• Superficie del Terreno: 3.251 m²\n• Superficie Cubierta: 200 m²\n• Estado general: Excelente.\n\nCasa Principal: 3 Dormitorios (uno con placard) | Living con salamandra | Cocina comedor diario | 1 Baño completo | Quincho con parrilla | Living de exterior | Piscina de fibra de vidrio | Parque parquizado, iluminado y con juegos infantiles.\n\nDepartamento: 2 Dormitorios | Cocina / Comedor / Living integrados | Piscina de fibra de vidrio propia | Servicios independientes: Medidor de luz propio y perforación de agua | Entrada totalmente independiente por calle Copahue.\n\nIVANA MOLINA & ASOC. BIENES RAÍCES\nMAT 1048 – CDMDLM',
    beds: 5,
    baths: 2,
    area: '3.251 m²',
    features: ['Lote en Esquina 3.251 m²', 'Depto. Alquilado hasta Sep 2026', 'Doble Piscina de Fibra de Vidrio', 'Subdivisión en Trámite', 'Quincho con Parrilla', 'Servicios Independientes'],
    coordinates: { x: 38, y: 42 },
    isFeatured: true,
    isMostWanted: true,
  },
  {
    id: 'prop-14',
    transactionType: 'venta',
    title: 'Dos Casas Quintas – Girardot 1345',
    subtitle: 'Dos ingresos independientes sobre 1.495 m² – 20 de Junio',
    price: 'Consultar Precio',
    priceNumeric: 0,
    location: '20 de Junio, La Matanza',
    streets: 'Girardot esq. Castro',
    mercadoLibreLink: 'https://casa.mercadolibre.com.ar/MLA-1592415569-casa-quinta-en-venta-en-20-de-junio-_JM',
    category: 'casas-quinta',
    image: '/venta/casas-quinta/girardot-1345/PORTADA (2).webp',
    images: [
      '/venta/casas-quinta/girardot-1345/PORTADA (2).webp',
      '/venta/casas-quinta/girardot-1345/1 (2).webp',
      '/venta/casas-quinta/girardot-1345/2 (3).webp',
      '/venta/casas-quinta/girardot-1345/3.webp',
      '/venta/casas-quinta/girardot-1345/4.webp',
      '/venta/casas-quinta/girardot-1345/5.webp',
      '/venta/casas-quinta/girardot-1345/6.webp',
      '/venta/casas-quinta/girardot-1345/7.webp',
      '/venta/casas-quinta/girardot-1345/8.webp',
      '/venta/casas-quinta/girardot-1345/9.webp',
      '/venta/casas-quinta/girardot-1345/10.webp',
      '/venta/casas-quinta/girardot-1345/11.webp',
      '/venta/casas-quinta/girardot-1345/12.webp',
    ],
    description: 'Casa en venta en 20 de Junio, La Matanza –\nDos casas quintas con ingresos independientes sobre 1.495 m² totales\n\nPropiedad compuesta por dos casas linderas, cada una con acceso propio, ubicadas en entorno residencial, parquizado y con cerco perimetral natural.\n\nCasa sobre calle Castro 911:\n• Cocina integrada al living comedor\n• 2 dormitorios y baño completo\n• Galería semicubierta\n• Piscina de 7 x 3 con venecitas\n• Quincho con parrilla, baño exterior y cuarto de guardado\n• Superficie cubierta: 82 m²\n\nCasa alpina sobre Girardot esq. Castro:\n• Ambiente integrado y altillo/dormitorio\n• Baño completo\n• Amplio quincho con parrilla y portón corredizo\n• Piscina instalada y pérgola\n• Superficie cubierta: 92 m²\n\nDatos generales:\n• Terrenos parquizados de 720 m² cada uno\n• Servicio de luz\n• Total: 3 dormitorios – 4 baños – 2 cocheras\n\nIdeal para dos familias, renta, turismo o vivienda con amplio parque.\n\nIVANA MOLINA & ASOC. BIENES RAICES\nMAT 1048\nCDMDLM',
    beds: 3,
    baths: 4,
    area: '1.495 m²',
    features: ['2 Casas con Ingresos Independientes', '2 Piscinas (una con venecitas)', '2 Quinchos con Parrilla', 'Terrenos de 720 m² c/u', '2 Cocheras', 'Ideal para Renta o Turismo'],
    coordinates: { x: 43, y: 50 },
    isFeatured: true,
    isMostWanted: true,
  },
  {
    id: 'prop-15',
    transactionType: 'alquiler',
    title: 'Local Comercial',
    subtitle: 'De Los Franceses Nro 3740',
    price: 'Consultar Precio',
    priceNumeric: 0,
    location: 'La Matanza',
    streets: 'De Los Franceses 3740',
    mercadoLibreLink: '',
    category: 'locales',
    image: '/alquiler/locales/De-Los-Franceses-Nro-3740/PORTADA.webp',
    images: [
      '/alquiler/locales/De-Los-Franceses-Nro-3740/PORTADA.webp',
      '/alquiler/locales/De-Los-Franceses-Nro-3740/1.webp',
      '/alquiler/locales/De-Los-Franceses-Nro-3740/2.webp',
      '/alquiler/locales/De-Los-Franceses-Nro-3740/3 (1).webp',
      '/alquiler/locales/De-Los-Franceses-Nro-3740/3.webp',
      '/alquiler/locales/De-Los-Franceses-Nro-3740/4.webp'
    ],
    description: 'ALQUILER DE LOCAL PARA USO COMERCIAL - Inmueble ubicado en De Los Franceses Nro 3740\n\nDESCRIPCIÓN:\nLOCAL CON BAÑO COMPLETO 30 M2 APROXIMADAMENTE – FRENTE VIDRIADO CON PERSIANA METALICA MICRO – PERFORADA “MANUAL” - ESPACIO DE DEPOSITO.\n\nPeriodo de alquiler 2 años aumento cada 3 meses de acuerdo al índice de precios al consumidor (IPC) con un mínimo del 10%.\n\nREQUISITOS PARA INGRESO:\n• MES DE INGRESO\n• MES DE DEPOSITO DE GARANTÍA\n• MES DE HONORARIOS (INTERMEDIACIÓN INMOBILIARIA)\n\nGASTOS ADMINISTRATIVOS:\nPEDIDOS DE INFORMES – SELLADO DE ARBA.\n\nGARANTÍAS:\n• GARANTÍA PROPIETARIA\n• 3 RECIBOS DE SUELDO\n• SEGURO DE CAUCIÓN',
    beds: 0,
    baths: 1,
    area: '30 m²',
    features: ['Baño completo', 'Frente vidriado', 'Persiana metálica', 'Espacio de depósito'],
    coordinates: { x: 50, y: 50 },
    isFeatured: true,
    isMostWanted: false,
  },
  {
    id: 'prop-17',
    transactionType: 'venta',
    title: 'Aguapey',
    subtitle: 'Casa en Venta – 20 de Junio',
    price: 'Consultar Precio',
    priceNumeric: 0,
    location: '20 de Junio',
    streets: 'Aguapey',
    mercadoLibreLink: '',
    category: 'casas',
    image: '/venta/casas-quinta/aguapey-venta/1.webp',
    images: [
      '/venta/casas-quinta/aguapey-venta/1.webp',
      '/venta/casas-quinta/aguapey-venta/2.webp',
      '/venta/casas-quinta/aguapey-venta/3.webp',
      '/venta/casas-quinta/aguapey-venta/4.webp',
      '/venta/casas-quinta/aguapey-venta/5.webp',
      '/venta/casas-quinta/aguapey-venta/6.webp',
      '/venta/casas-quinta/aguapey-venta/7.webp',
      '/venta/casas-quinta/aguapey-venta/8.webp',
      '/venta/casas-quinta/aguapey-venta/9.webp'
    ],
    description: '🏡 CASA EN VENTA | 20 DE JUNIO 🌿\n\nViví rodeado de naturaleza, privacidad y confort en esta hermosa propiedad desarrollada sobre un amplio lote de 1.316 m², totalmente alambrado y parquizado.\n\nLa vivienda cuenta con 114 m² cubiertos, construida con doble pared de ladrillo visto y aberturas de PVC con DVH, ofreciendo excelente calidad constructiva y confort térmico.\n\n📍 Distribución\n- Amplio ambiente integrado de cocina, comedor y living con salamandra a leña.\n- Habitación principal en suite con vestidor.\n- Toilette.\n- Galería semicubierta que funciona como cochera techada y quincho, ideal para disfrutar de reuniones al aire libre.\n\nCon orientación norte, la propiedad brinda una excelente iluminación natural durante todo el día.\n\n🚗 Características\n- Terreno de 1.316 m² totalmente cercado y parquizado.\n- 1 dormitorio.\n- 2 baños.\n- Cochera semicubierta.\n- Antigüedad: 8 años, con muy buen estado de mantenimiento.\n\n📍 Apta crédito hipotecario.',
    beds: 1,
    baths: 2,
    area: '1.316 m²',
    features: ['Apta crédito', 'Parquizado', 'Salamandra a leña', 'Aberturas PVC con DVH', 'Quincho'],
    coordinates: { x: 45, y: 55 },
    isFeatured: true,
    isMostWanted: false,
  },
  {
    id: 'prop-18',
    transactionType: 'venta',
    title: 'Depto Laprida 375',
    subtitle: 'Departamento de 2 ambientes - Ramos Mejía',
    price: 'Consultar Precio',
    priceNumeric: 0,
    location: 'Ramos Mejía',
    streets: 'Laprida 375',
    mercadoLibreLink: 'https://departamento.mercadolibre.com.ar/MLA-1847129655-venta-de-departamento-ramos-mejia-2-ambientes-planta-baja-apto-credito-_JM',
    category: 'departamentos',
    image: '/venta/casas-quinta/laprida-375-ramos/1.webp',
    images: [
      '/venta/casas-quinta/laprida-375-ramos/1.webp',
      '/venta/casas-quinta/laprida-375-ramos/2.webp',
      '/venta/casas-quinta/laprida-375-ramos/3.webp',
      '/venta/casas-quinta/laprida-375-ramos/4.webp',
      '/venta/casas-quinta/laprida-375-ramos/5.webp',
      '/venta/casas-quinta/laprida-375-ramos/5 (1).webp',
      '/venta/casas-quinta/laprida-375-ramos/6.webp',
      '/venta/casas-quinta/laprida-375-ramos/7.webp',
      '/venta/casas-quinta/laprida-375-ramos/8.webp',
      '/venta/casas-quinta/laprida-375-ramos/9.webp',
      '/venta/casas-quinta/laprida-375-ramos/10.webp',
      '/venta/casas-quinta/laprida-375-ramos/11.webp',
      '/venta/casas-quinta/laprida-375-ramos/12.webp',
      '/venta/casas-quinta/laprida-375-ramos/13.webp',
      '/venta/casas-quinta/laprida-375-ramos/14.webp'
    ],
    description: '🏡 DEPARTAMENTO DE PRIMERA CATEGORÍA EN VENTA\n\nSi buscás diseño, calidad constructiva y confort, este departamento de 2 ambientes es una excelente oportunidad.\n\n📐 Cuenta con 38 m² cubiertos y 15 m² descubiertos, distribuidos en:\n- Luminoso living-comedor con cocina integrada.\n- Dormitorio con placard.\n- Baño completo.\n- Patio privado con parrilla y lavadero.\n\n🌿 Sus ambientes se destacan por su excelente iluminación natural y muy buena ventilación.\n\nDetalles de categoría\n- Griferías y sanitarios de primera calidad.\n- Cerramientos de PVC con DVH.\n- Persiana motorizada y manual en el contrafrente.\n- Instalación oculta para aire acondicionado.\n\n📍 Información adicional\n- Edificio de Primera Categoría.\n- 1.º piso.\n- Estado general: Excelente.',
    beds: 1,
    baths: 1,
    area: '53 m²',
    features: ['Patio con parrilla', 'Apto crédito', 'Cerramientos DVH', 'Primera Categoría'],
    coordinates: { x: 50, y: 50 },
    isFeatured: true,
    isMostWanted: false,
  },
  {
    id: 'prop-19',
    transactionType: 'venta',
    title: 'Gibraltar',
    subtitle: 'Casa con potencial para refaccionar',
    price: 'Consultar Precio',
    priceNumeric: 0,
    location: 'Pontevedra, Merlo',
    streets: 'Gibraltar',
    mercadoLibreLink: 'https://casa.mercadolibre.com.ar/MLA-1783986083-casa-en-venta-terreno-390m2-merlo-pontevedra-_JM',
    category: 'casas',
    image: '/venta/casas-quinta/Gibraltar-1-pontevedra/1.webp',
    images: [
      '/venta/casas-quinta/Gibraltar-1-pontevedra/1.webp',
      '/venta/casas-quinta/Gibraltar-1-pontevedra/2.webp',
      '/venta/casas-quinta/Gibraltar-1-pontevedra/3.webp',
      '/venta/casas-quinta/Gibraltar-1-pontevedra/4.webp',
      '/venta/casas-quinta/Gibraltar-1-pontevedra/5.webp'
    ],
    description: '🏡 CASA EN VENTA | GRAN POTENCIAL PARA REFACCIONAR O AMPLIAR\n\n¡Una excelente oportunidad para invertir o crear el hogar que siempre imaginaste!\n\n📍 Ubicada a solo una cuadra y media del asfalto, con muy buen acceso, esta propiedad se desarrolla sobre un terreno de 390 m², ideal para futuras ampliaciones o proyectos.\n\n📐 La vivienda cuenta con 60 m² cubiertos, distribuidos en:\n- Amplio ambiente integrado de cocina, comedor y living.\n- 2 dormitorios.\n- 1 baño.\n- Galería techada.\n\n🌿 Su amplio lote y la distribución actual ofrecen una base ideal para reciclar, refaccionar o ampliar según tus necesidades.\n\n💬 ¡El propietario escucha ofertas!',
    beds: 2,
    baths: 1,
    area: '390 m²',
    features: ['A refaccionar', 'Lote de 390 m²', 'Galería techada'],
    coordinates: { x: 55, y: 45 },
    isFeatured: false,
    isMostWanted: false,
  },
  {
    id: 'prop-20',
    transactionType: 'venta',
    title: 'Gibraltar 2',
    subtitle: 'Oportunidad para invertir o ampliar',
    price: 'Consultar Precio',
    priceNumeric: 0,
    location: 'Pontevedra, Merlo',
    streets: 'Gibraltar',
    mercadoLibreLink: 'https://casa.mercadolibre.com.ar/MLA-1783949139-casa-en-venta-terreno-de-390m2-pontevedra-merlo-_JM',
    category: 'casas',
    image: '/venta/casas-quinta/Gibraltar-2-pontevedra/1 PORTADA.webp',
    images: [
      '/venta/casas-quinta/Gibraltar-2-pontevedra/1 PORTADA.webp',
      '/venta/casas-quinta/Gibraltar-2-pontevedra/1.webp',
      '/venta/casas-quinta/Gibraltar-2-pontevedra/2.webp',
      '/venta/casas-quinta/Gibraltar-2-pontevedra/4.webp',
      '/venta/casas-quinta/Gibraltar-2-pontevedra/5.webp'
    ],
    description: '🏡 CASA EN VENTA | OPORTUNIDAD PARA INVERTIR O AMPLIAR\n\nSi buscás una propiedad con gran potencial, esta casa es una excelente opción para reciclar, refaccionar o desarrollar un nuevo proyecto.\n\n📍 Ubicada a solo una cuadra y media del asfalto, con muy buen acceso, sobre un terreno de 390 m² que brinda amplias posibilidades de crecimiento.\n\n📐 La vivienda cuenta con 60 m² cubiertos, distribuidos en:\n- Amplio ambiente integrado de cocina, comedor y living.\n- 1 dormitorio.\n- 1 baño.\n- Galería techada.\n\n🌿 Un lote amplio y una distribución funcional que convierten a esta propiedad en una excelente oportunidad para quienes buscan invertir o proyectar una ampliación.\n\n💬 ¡El propietario escucha ofertas!',
    beds: 1,
    baths: 1,
    area: '390 m²',
    features: ['Oportunidad', 'Lote de 390 m²', 'Galería techada'],
    coordinates: { x: 55, y: 46 },
    isFeatured: false,
    isMostWanted: false,
  },
  {
    id: 'prop-21',
    transactionType: 'venta',
    title: 'Urien',
    subtitle: 'Casa Quinta en Venta',
    price: 'Consultar Precio',
    priceNumeric: 0,
    location: '20 de Junio, La Matanza',
    streets: 'Urien',
    mercadoLibreLink: 'https://inmueble.mercadolibre.com.ar/MLA-2402489924-casa-quinta-en-venta-20-de-junio-terreno-1500-m2-_JM',
    category: 'casas-quinta',
    image: '/venta/casas-quinta/Urien-casa-quinta-20-de-junio/1.webp',
    images: [
      '/venta/casas-quinta/Urien-casa-quinta-20-de-junio/1.webp',
      '/venta/casas-quinta/Urien-casa-quinta-20-de-junio/2.webp',
      '/venta/casas-quinta/Urien-casa-quinta-20-de-junio/3.webp',
      '/venta/casas-quinta/Urien-casa-quinta-20-de-junio/4.webp',
      '/venta/casas-quinta/Urien-casa-quinta-20-de-junio/5.webp',
      '/venta/casas-quinta/Urien-casa-quinta-20-de-junio/6.webp',
      '/venta/casas-quinta/Urien-casa-quinta-20-de-junio/7.webp',
      '/venta/casas-quinta/Urien-casa-quinta-20-de-junio/8.webp',
      '/venta/casas-quinta/Urien-casa-quinta-20-de-junio/9.webp',
      '/venta/casas-quinta/Urien-casa-quinta-20-de-junio/10.webp',
      '/venta/casas-quinta/Urien-casa-quinta-20-de-junio/11.webp',
      '/venta/casas-quinta/Urien-casa-quinta-20-de-junio/12.webp',
      '/venta/casas-quinta/Urien-casa-quinta-20-de-junio/13.webp',
      '/venta/casas-quinta/Urien-casa-quinta-20-de-junio/14.webp'
    ],
    description: '🏡 CASA QUINTA EN VENTA | 20 DE JUNIO\n\nSi buscás espacio, comodidad y un entorno ideal para disfrutar en familia, esta propiedad es para vos.\n\nDesarrollada sobre un lote de 1.500 m² con 200 m² cubiertos, construida en ladrillo a la vista con techos de teja y garage cubierto para 3 vehículos.\n\n📍 Distribución\n- Planta alta: 2 dormitorios, baño completo y sala de estar tipo living con excelente iluminación natural.\n- Planta baja: 2 dormitorios, baño y amplio ambiente integrado de cocina, comedor y living.\n\n🌳 Exterior\n- Quincho de 9 × 7,50 m con lavadero y baño.\n- Piscina de aproximadamente 15 × 5 m con playa húmeda, ideal para disfrutar del verano.\n\n📌 Ubicación\nA solo 1 cuadra y media del asfalto, frente a la Subcomisaría de 20 de Junio, con acceso y proyección de asfaltado.\n\n💡 Servicios\n- Electricidad\n- Internet y TV (Telecentro)\n\n🛋 Se vende con mobiliario.\n\n💬 ¡Se escuchan ofertas!',
    beds: 4,
    baths: 2,
    area: '1.500 m²',
    features: ['Piscina', 'Quincho', 'Garage para 3 vehículos', 'Amueblada'],
    coordinates: { x: 48, y: 52 },
    isFeatured: true,
    isMostWanted: true,
  },
  {
    id: 'prop-22',
    transactionType: 'alquiler',
    title: 'Depto Canning Center',
    subtitle: 'Departamento 2 Ambientes Amoblado',
    price: 'Consultar Precio',
    priceNumeric: 0,
    location: 'Canning',
    streets: 'Canning Center',
    mercadoLibreLink: '',
    category: 'departamentos',
    status: 'alquilada',
    image: '/alquiler/departamentos/DEPTO-CANNING/1.webp',
    images: [
      '/alquiler/departamentos/DEPTO-CANNING/1.webp',
      '/alquiler/departamentos/DEPTO-CANNING/2.webp',
      '/alquiler/departamentos/DEPTO-CANNING/3.webp',
      '/alquiler/departamentos/DEPTO-CANNING/4.webp',
      '/alquiler/departamentos/DEPTO-CANNING/5.webp',
      '/alquiler/departamentos/DEPTO-CANNING/6.webp',
      '/alquiler/departamentos/DEPTO-CANNING/7.webp'
    ],
    description: 'Alquiler | Departamento 2 Ambientes Amoblado en Canning Center\nViví con el confort y la comodidad que ofrece uno de los complejos más exclusivos de Canning.\nEste moderno departamento de 2 ambientes se entrega totalmente amoblado y equipado. Cuenta con un luminoso living-comedor con cocina integrada, dormitorio con placard, baño completo y balcón con excelente ventilación e iluminación natural. Además, incluye cochera y baulera, aires acondicionados en todos los ambientes y cortinas instaladas.\nCanning Center combina diseño, calidad y una ubicación estratégica, ofreciendo seguridad permanente, piscina climatizada, solárium, dos salones de usos múltiples (SUM), seis ascensores de última generación y un completo paseo comercial con primeras marcas y servicios.\nLa unidad se distingue por sus terminaciones de calidad, con pisos de porcelanato, aberturas de PVC con doble vidrio hermético (DVH) para un excelente aislamiento térmico y acústico, y balcón semicubierto con conexión para parrilla a gas.\n\nIVANA MOLINA & ASOC. BIENES RAÍCES\nMartillera y Corredora Pública – Mat. 1048\nColegio de Martilleros de La Matanza',
    beds: 1,
    baths: 1,
    area: '2 Amb',
    features: ['Amoblado', 'Cochera y baulera', 'Piscina climatizada', 'Aberturas PVC DVH', 'Balcón con parrilla'],
    coordinates: { x: 50, y: 50 },
    isFeatured: true,
    isMostWanted: false,
  },
  {
    id: 'prop-23',
    transactionType: 'venta',
    title: 'PH Frente a la Plaza',
    subtitle: 'En el corazón de Caseros',
    price: 'Consultar Precio',
    priceNumeric: 0,
    location: 'Caseros, Tres de Febrero',
    streets: 'Frente a la plaza',
    mercadoLibreLink: 'https://inmueble.mercadolibre.com.ar/MLA-2834035530-ph-en-venta-balcon-frente-a-la-plaza-caseros-centro-_JM',
    category: 'casas',
    image: '/venta/casas-quinta/carlos-tejedor-caseros/1.webp',
    images: [
      '/venta/casas-quinta/carlos-tejedor-caseros/1.webp',
      '/venta/casas-quinta/carlos-tejedor-caseros/2.webp',
      '/venta/casas-quinta/carlos-tejedor-caseros/3.webp',
      '/venta/casas-quinta/carlos-tejedor-caseros/4.webp',
      '/venta/casas-quinta/carlos-tejedor-caseros/5.webp',
      '/venta/casas-quinta/carlos-tejedor-caseros/6.webp',
      '/venta/casas-quinta/carlos-tejedor-caseros/7.webp',
      '/venta/casas-quinta/carlos-tejedor-caseros/8.webp',
      '/venta/casas-quinta/carlos-tejedor-caseros/9.webp',
      '/venta/casas-quinta/carlos-tejedor-caseros/10.webp',
      '/venta/casas-quinta/carlos-tejedor-caseros/11.webp'
    ],
    description: '🏡 PH en venta frente a la plaza, en el corazón de Caseros\n\nSi buscás amplitud, comodidad y una ubicación privilegiada, esta propiedad es para vos.\n\n155 m² aproximados distribuidos en dos plantas:\n✔️ 3 dormitorios con placard\n✔️ Amplio living comedor con balcón y vista abierta a la plaza\n✔️ Cocina comedor\n✔️ 2 baños completos\n✔️ Playroom o sala de estar\n✔️ Patio con lavadero cubierto\n✔️ Terraza con parrilla\n✔️ Entrada totalmente independiente\n\nUna propiedad muy luminosa, con excelente ventilación y en impecable estado, ubicada cerca de comercios, medios de transporte y todos los servicios.\n\n📩 Consultanos para más información o coordiná tu visita.\n\nIVANA MOLINA & ASOC. BIENES RAÍCES\nMAT 1048\nCOLEGIO DE MARTILLEROS DE LA MATANZA',
    beds: 3,
    baths: 2,
    area: '155 m²',
    features: ['Terraza con parrilla', 'Entrada independiente', 'Frente a la plaza', 'Playroom'],
    coordinates: { x: 50, y: 50 },
    isFeatured: true,
    isMostWanted: true,
  }
];

export const testimonials: Testimonial[] = [
  {
    id: 'test-1',
    name: 'Alexander Sterling',
    role: 'Inversor en Tecnología Financiera',
    text: '“La reserva y el nivel de detalle en su asesoría superaron mis expectativas. Consiguieron una residencia brutalista exclusiva fuera del mercado y concretaron la compra en pocos días con total discreción.”',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    rating: 5,
  },
  {
    id: 'test-2',
    name: 'Dra. Elena Rostova',
    role: 'Coleccionista de Arte y Filántropa',
    text: '“Vila Lumina es una obra de arte y una extensión de mi galería. La luz natural y la amplitud de los espacios son extraordinarias. Su servicio personalizado es clave para adquirir propiedades de verdadero prestigio internacional.”',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
    rating: 5,
  },
  {
    id: 'test-3',
    name: 'Kenji y Sakura Sato',
    role: 'Inversores en Bienes de Lujo',
    text: '“Adquirir el lote Terra Sanctum con planos aprobados fue nuestra mejor decisión del año. Su comprensión del mercado premium y su acompañamiento legal y técnico simplificaron una operación compleja con absoluta seguridad.”',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=200&q=80',
    rating: 5,
  },
];

export const stats: Stat[] = [
  {
    id: 'stat-1',
    label: 'Inversiones Concretadas',
    value: 124,
    suffix: 'M+',
    prefix: '$',
  },
  {
    id: 'stat-2',
    label: 'Clientes Satisfechos',
    value: 85,
    suffix: '',
  },
  {
    id: 'stat-3',
    label: 'Años de Trayectoria',
    value: 12,
    suffix: '+',
  },
  {
    id: 'stat-4',
    label: 'Transacciones Exitosas',
    value: 99.4,
    suffix: '%',
  },
];
